 pool: 
  vmImage: windows-2019

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'release'
  major: 1
  minor: 0
  build: 0

steps:

#- powershell: |
#     # Update appxmanifest. This must be done before the build.
#     [xml]$manifest= get-content ".\HeadTraxPackage\Package.appxmanifest"
#     $manifest.Package.Identity.Version = "$(major).$(minor).$(build).$(revision)"
#     $manifest.save(".\HeadTraxPackage\Package.appxmanifest")
#  displayName: 'Version Package Manifest'

- task: MSBuild@1
  inputs:
    solution: src\WvdMigration\MsixPackage.wapproj
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)
    msbuildArguments: '/restore /p:UapAppxPackageBuildMode=$(MsixBuildMode) /p:AppxPackageOutput=$(Build.ArtifactStagingDirectory)/WvdMigration.msix'
    maximumCpuCount: false
  displayName: 'Package the App'

- task: DownloadSecureFile@1
  name : cert
  inputs:
    secureFile: 'MsixPackage_TemporaryKey.pfx'
  displayName: 'Download Secure PFX File'
  
- script: '"C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\signtool"
    sign /fd SHA256 /f $(Agent.TempDirectory)/MsixPackage_TemporaryKey.pfx $(Build.ArtifactStagingDirectory)/WvdMigration.msix'
  displayName: 'Sign MSIX Package'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
